### ISSUE TITLE
Build input files cannot be found 

### ISSUE THREAD

**Issue by bentettmar** [cryptoAlgorithm/Swiftcord#5]
Some files that are required to build the program are not found in the repo but xcode knows they should be there.  
The files that are required are:
- views/ServerButton.swift
- views/ServerView.swift
- utils/CodableThrowable.swift

**Comment by cryptoAlgorithm** [comment]
@bentettmar it seems like you haven't been responding to this issue. I'll close it in a day or 2 if there are no further comments.

**Comment by bentettmar** [comment]
> Hi there! I just confirmed building from source works, with the following commands:
> 
> ```shell
> git clone https://github.com/cryptoAlgorithm/Swiftcord
> cd Swiftcord
> xcodebuild # After awhile the build succeeds with ** BUILD SUCCEEDED **
> ls # Note the presence of the build directory
> ls ./build/Release # Note the presence of Swiftcord.app
> ```
> 
> Please note that these steps only confirm that the project can be built, but the .app it produces cannot run since it lacks signing. Could you please try the steps above, or try again in Xcode in a freshly cloned version? The files missing seems outdated, `Utils/CodableThrowable.swift` has been renamed to `Utils/DecodableThrowable.swift` for example.

When i tried to build Swiftcord using `xcodebuild` i got an error related to importing lottie but when i opened it in xcode and built it i didnt get any errors related to the files being missing. 

So currently everything build wise is working, thanks.

**Comment by cryptoAlgorithm** [comment]
Ok, glad to hear everything works out. Please make sure you're always building the latest version of the source code, since there are major bug fixes, at this stage, every commit

**Comment by bentettmar** [comment]
Okay, ive found a couple bugs as well but ill make their own issues.
