### ISSUE TITLE
Pre-built releases would be nice

### ISSUE THREAD

**Issue by aviwad** [cryptoAlgorithm/Swiftcord#6]
Not a bug just an extra feature request! Perhaps connecting with GitHub Actions so a new release is built on every new version/milestone. Because right now building the entire project would be quite a hassle, and as the other issue states, building isn't possible in the current state. Awesome project btw looks so much like the original Discord app. Great work!!

**Comment by cryptoAlgorithm** [comment]
For instance, running `xcodebuild` produces a release .app, but attempting to run it raises this error:
<img width="372" alt="Screen Shot 2022-04-12 at 3 50 28 PM" src="https://user-images.githubusercontent.com/64193267/162909124-c9375b0b-15f2-4cd1-804a-0056220a99f0.png">

**Comment by cryptoAlgorithm** [comment]
@aviwad, I've just released the first pre-built release, check it out at [releases](https://github.com/cryptoAlgorithm/Swiftcord/releases/latest)! It contains a pre-built, universal .app package.

**Comment by aviwad** [comment]
Awesome!! runs really well. love the settings page right now lol.

**Comment by cryptoAlgorithm** [comment]
Thanks, appreciate it! xD
