### ISSUE TITLE
Flaky Gateway Connectivity

### ISSUE THREAD

**Issue by bentettmar** [cryptoAlgorithm/Swiftcord#8]
When loading channels i get this error
```
<E> [DiscordGateway] Unknown close code: 1000
2022-04-13 07:18:59.697935+0100 Swiftcord[37958:1482007] [SwiftUI] Publishing changes from background threads is not allowed; make sure to publish values from the main thread (via operators like receive(on:)) on model updates.
```
and when looking into xcode
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/83777519/163114111-53d92d5f-5e80-4d8d-be65-1c93d66882e2.png">

Im not sure if this warning is turning into an error or not due to my account having server folders and Swiftcord not supporting that just yet or its an actual error. So i have 2 questions. How do i log out of my account before fully loading in? and Is there a way to solve this warning?

**Comment by bentettmar** [comment]
Ok i made a way to log out by copying the log out btn from user settings onto the loading view.

**Comment by bentettmar** [comment]
So the error is not related to server folders, ill try my best to solve it but its here if anyone is able to help.

**Comment by cryptoAlgorithm** [comment]
@bentettmar, these warnings are due to me trying out a performance optimization, and do not impact functionality (you can just ignore them, in my testing). Swiftcord simply ignores server folders, so that shouldn't cause problems. To help me debug this issue, could you send more of the logs?

Also, you might want to try the newly-created `native-urlsession-websocket` branch which contains fixes for the warnings, and potentially has performance increases. Reconnection is not implemented yet, so if you disconnect the Gateway will never reconnect until you restart Swiftcord.

**Comment by cryptoAlgorithm** [comment]
It's quite puzzling that the socket is closing with code 1000, since discord close codes usually are in the range 400x. I'll need more of the log to debug this, up to and after the close code error. Please also try the new branch, that might be easier to debug

**Comment by bentettmar** [comment]
It closes after a while of receiving discord's gateway message events.
heres the full log: https://pastebin.com/R8NETuKW

**Comment by bentettmar** [comment]
I will try out the `native-urlsession-websocket` branch

**Comment by bentettmar** [comment]
After updating to the new branch, i get this error being spammed in the console.
```
<D> [DiscordGateway] Resume called
<E> [DiscordGateway] Connection error: Optional(Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected" UserInfo={NSErrorFailingURLStringKey=https://gateway.discord.gg/?v=9&encoding=json, NSErrorFailingURLKey=https://gateway.discord.gg/?v=9&encoding=json})
```
I did also enable incoming connections but that didnt seem to do anything.

**Comment by cryptoAlgorithm** [comment]
Ok, I'm seeing a common trend of issues here: nothing is received by the WebSocket, so it eventually kills the connection.

**Comment by cryptoAlgorithm** [comment]
What were the messages before that error gets spammed in the console?

**Comment by cryptoAlgorithm** [comment]
> I did also enable incoming connections but that didnt seem to do anything.

Was it not already enabled? If it wasn't, I think I see the issue now. But still, please send me the log before the error starts spamming.

**Comment by bentettmar** [comment]
trying to copy the log crashed xcode...
one second

**Comment by bentettmar** [comment]
Heres the full log: https://pastebin.com/XaWTLeHF
It also spams this as well:
<img width="577" alt="image" src="https://user-images.githubusercontent.com/83777519/163152858-47430b41-2412-4ce3-a1fc-48bf03e31c11.png">

**Comment by cryptoAlgorithm** [comment]
It seems like the gateway is randomly disconnecting. Do you have a stable internet connection?

**Comment by cryptoAlgorithm** [comment]
Yeah, the spamming is a side-effect of my incorrect handling of close events. The only conclusion I can get is the websocket disconnects randomly, and without any reason. What you could try to do, is to log the receive closure to get a better idea of the messages coming in
<img width="540" alt="Screen Shot 2022-04-13 at 6 07 08 PM" src="https://user-images.githubusercontent.com/64193267/163155372-caa1bc1b-7ab4-4935-828e-f3e0b7f932b0.png">

<img width="823" alt="Screen Shot 2022-04-13 at 6 08 22 PM" src="https://user-images.githubusercontent.com/64193267/163155583-a3168f6d-ed8e-4259-9327-1084778f2cc5.png">
Logging the reason and close code here can shed some light on the issue as well,

<img width="476" alt="Screen Shot 2022-04-13 at 6 09 36 PM" src="https://user-images.githubusercontent.com/64193267/163155768-178ed1cb-6332-4c6e-96d3-31a5d89c290e.png">
And finally, removing the cases for .error, .cancelled and .binary should fix the spamming issue (but does not fix the root issue of the socket disconnecting)

**Comment by bentettmar** [comment]
Ok ill take a look at it next time i have time. Thanks for the input.

**Comment by cryptoAlgorithm** [comment]
Ok, hopefully you can sort out this issue :D. This is a weird case I've never met before, after testing it on numerous accounts and different network conditions.

**Comment by MontereySand** [comment]
god I wish I knew I how to code, this stuff is awesome I'll pitch in during summer when school is over for sure! love your work

**Comment by cryptoAlgorithm** [comment]
Hey, @bentettmar, I completely rewrote the underlying WebSocket wrapper class, which should hopefully increase its reliability. You could try pulling the latest commits from the `native-urlsession-websocket` branch and building it again, and seeing if the issue persists.

**Comment by bentettmar** [comment]
I pulled the `native-urlsession-websocket` branch but during build i get this error
```
error: Build input file cannot be found: '/Macintosh HD/Users/vinkwok/XcodeProjects/Swiftcord/Swiftcord/Utils/LoggerInit.swift' (in target 'Swiftcord' from project 'Swiftcord')
```

**Comment by bentettmar** [comment]
Fixed in discord.
